sudo: required
language: python
python:
  - "3.7-dev"
services:
  - docker

stages:
  - docker-build

# Installs dependencies
install:
  - pip install -r requirements.txt

jobs:
  include:
  - stage: docker-build
    script:
    - docker build -t adamukaapan/gavariabot-core .
