sudo: required
language: python
python:
  - "3.7-dev"
services:
  - docker

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/513938854173081600/P3zmcoobUDzdjn4QGHqL2kIGNLmnjbJyfm_EPC9lH2vaQy-u-2FnIzTHFhQa9EXiggVr
    on_success: always
    on_failure: always
    on_error: always

# Installs dependencies
install:
  - pip install -r requirements.txt

script:
  - docker build -t adamukaapan/gavariabot-core .
