sudo: required
language: python
python:
  - "3.7-dev"
services:
  - docker

# Installs dependencies
install:
  - pip install -r requirements.txt

script:
  - docker build -t adamukaapan/gavariabot-core .
